// List of components user can select from
export const componentList = [
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsTotalDai',
    description: 'Total amount of Dai in existence',
    id: 0,
    isFirstInCategory: true, // used for displaying headers
    name: 'Total Dai',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsDaiPrice',
    description: 'Current price of Dai',
    id: 1,
    isFirstInCategory: false,
    name: 'Dai Price',
    source: 'CoinGecko API',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsBatPrice',
    description: 'Current price of BAT',
    id: 2,
    isFirstInCategory: false,
    name: 'BAT Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsEthPrice',
    description: 'Current price of Ether',
    id: 3,
    isFirstInCategory: false,
    name: 'Ether Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsMkrPrice',
    description: 'Current price of Maker',
    id: 4,
    isFirstInCategory: false,
    name: 'Maker Price',
    source: 'CoinGecko API',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsBatSf',
    description: 'BAT Stability Fee',
    id: 5,
    isFirstInCategory: false,
    name: 'BAT Stability Fee',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsEthSf',
    description: 'ETH Stability Fee',
    id: 6,
    isFirstInCategory: false,
    name: 'ETH Stability Fee',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsDsr',
    description: 'Dai Savings Rate',
    id: 7,
    isFirstInCategory: false,
    name: 'Dai Savings Rate',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsSurplus',
    description: 'System surplus, measured in Dai',
    id: 8,
    isFirstInCategory: false,
    name: 'System Surplus',
    source: 'Maker contracts',
  },
  // ETH Gas Station
  {
    category: 'Ethereum Network Stats',
    componentName: 'EgsGasPriceHighest',
    description: 'Gas price for fastest transactions',
    id: 9,
    isFirstInCategory: true,
    name: 'Fastest Gas Price',
    source: 'ETH Gas Station API',
  },
  {
    category: 'Ethereum Network Stats',
    componentName: 'EgsGasPriceHigh',
    description: 'Gas price for fast transactions',
    id: 10,
    isFirstInCategory: false,
    name: 'Fast Gas Price',
    source: 'ETH Gas Station API',
  },
  {
    category: 'Ethereum Network Stats',
    componentName: 'EgsGasPriceMedium',
    description: 'Gas price for average transactions',
    id: 11,
    isFirstInCategory: false,
    name: 'Average Gas Price',
    source: 'ETH Gas Station API',
  },
  {
    category: 'Ethereum Network Stats',
    componentName: 'EgsGasPriceLow',
    description: 'Gas price for safe low transactions',
    id: 12,
    isFirstInCategory: false,
    name: 'Safe Low Gas Price',
    source: 'ETH Gas Station API',
  },
  // Compound
  {
    category: 'Compound Stats',
    componentName: 'CompoundCdaiBorrow',
    description: 'cDAI borrow rate and total borrowed',
    id: 13,
    isFirstInCategory: true,
    name: 'cDAI Borrow Stats',
    source: 'Compound contracts',
  },
  {
    category: 'Compound Stats',
    componentName: 'CompoundCdaiSupply',
    description: 'cDAI supply rate and total supplied',
    id: 14,
    isFirstInCategory: false,
    name: 'cDAI Supply Stats',
    source: 'Compound contracts',
  },
  {
    category: 'Compound Stats',
    componentName: 'CompoundCusdcBorrow',
    description: 'cUSDC borrow rate and total borrowed',
    id: 15,
    isFirstInCategory: false,
    name: 'cUSDC Borrow Stats',
    source: 'Compound contracts',
  },
  {
    category: 'Compound Stats',
    componentName: 'CompoundCusdcSupply',
    description: 'cUSDC supply rate and total supplied',
    id: 16,
    isFirstInCategory: false,
    name: 'cUSDC Supply Stats',
    source: 'Compound contracts',
  },
];
