// List of components user can select from
export const componentList = [
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsTotalDai',
    description: 'Total amount of Dai in existence',
    id: 0,
    isFirstInCategory: true, // used for displaying headers
    name: 'Total Dai',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsDaiPrice',
    description: 'Current price of Dai',
    id: 1,
    isFirstInCategory: false,
    name: 'Dai Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsBatPrice',
    description: 'Current price of BAT',
    id: 2,
    isFirstInCategory: false,
    name: 'BAT Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsEthPrice',
    description: 'Current price of Ether',
    id: 3,
    isFirstInCategory: false,
    name: 'Ether Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsMkrPrice',
    description: 'Current price of Maker',
    id: 4,
    isFirstInCategory: false,
    name: 'Maker Price',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsBatSf',
    description: 'BAT Stability Fee',
    id: 5,
    isFirstInCategory: false,
    name: 'BAT Stability Fee',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsEthSf',
    description: 'ETH Stability Fee',
    id: 6,
    isFirstInCategory: false,
    name: 'ETH Stability Fee',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsDsr',
    description: 'Dai Savings Rate',
    id: 7,
    isFirstInCategory: false,
    name: 'Dai Savings Rate',
    source: 'Maker contracts',
  },
  {
    category: 'Dai and MakerDAO Stats',
    componentName: 'DaiStatsSurplus',
    description: 'System surplus, measured in Dai',
    id: 8,
    isFirstInCategory: false,
    name: 'System Surplus',
    source: 'Maker contracts',
  },
];
